feat: add https

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -3,7 +3,7 @@ name: Deploy to Server
 on:
   push:
     branches:
-      - main
+      - https
 permissions:
   contents: write
 
@@ -44,19 +44,36 @@ jobs:
           EOF
           
           scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r ./* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/watchlist-api
-
+      
+      # Obtaining SSL certificates for HTTPS
       - name: Install Certbot and obtain SSL certificates
         run: |
           ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
-            # Install Certbot
-            sudo apt-get update
-            sudo apt-get intall -y certbot
+            # Check if Certbot is installed
+            if ! command -v certbot &> /dev/null; then
+              echo "Certbot not found, installing..."
+              sudo apt-get update
+              sudo apt-get install -y certbot
+            else
+              echo "Certbot is already installed"
+            fi
           
-            # Obtain SSL cetificates
-            sudo certbot certonly --standalone --non-interactive --agree-tos -m ${{ secrets.YOUR_EMAIL }} -d ${{ secrets.SSH_HOST }}
-            
-            # Set up a cron job for automatic renewal          
-            (crontab -l ; echo "0 0,12 * * * certbot renew --post-hook 'systemctl restart nginx'") | crontab -
+            # Check if SSL certificates already exist
+            CERT_PATH="/etc/letsencrypt/live/${{ secrets.SSH_HOST }}/fullchain.pem"
+            if [ -f "$CERT_PATH" ]; then
+              echo "SSL certificates already exist, skipping certificate issuance"
+            else
+              echo "SSL certificates not found, obtaining new certificates..."
+              sudo certbot certonly --standalone --non-interactive --agree-tos -m ${{ secrets.YOUR_EMAIL }} -d ${{ secrets.SSH_HOST }}
+            fi
+          
+            # Ensure a cron job exists for automatic certificate renewal
+            if ! crontab -l | grep -q "certbot renew"; then
+              echo "Setting up a cron job for automatic certificate renewal..."
+              (crontab -l ; echo "0 0,12 * * * certbot renew --post-hook 'systemctl restart nginx'") | crontab -
+            else
+              echo "Cron job for certificate renewal is already set up"
+            fi
           EOF
 
       # Exporting environment variables and running docker compose
